name: WallJump
version: 2.0.2
main: com.tronmc.beta.WallJump
api-version: 1.19
softdepend: [WorldGuard, TreysDoubleJump]
authors: [ Arthed, MonsterWhat, MrTron ]
description: Adds an easy to understand, yet still challenging wall jump mechanic
commands:
  walljump:
    aliases: [wj, wjump]
